-- Wallet base tables for Barter Coins (closed-loop, in-app currency)
-- Design goals:
-- 1) Keep balances fast to read (`wallets`)
-- 2) Keep an immutable audit trail (`wallet_ledger_transactions`, `wallet_ledger_entries`)
-- 3) Keep operational controls configurable (`wallet_coin_limits`)

CREATE TABLE IF NOT EXISTS wallets (
    -- Owner of the wallet. One wallet per user.
    user_id VARCHAR(50) PRIMARY KEY REFERENCES user_registration_data(id) ON DELETE CASCADE,

    -- Spendable coin balance available for transfers/spends.
    available_balance BIGINT NOT NULL DEFAULT 0,

    -- Temporarily reserved coins (for future escrow/holds/disputes).
    locked_balance BIGINT NOT NULL DEFAULT 0,

    -- Lifetime total credited into the wallet (earn/tips/bonuses received).
    total_earned BIGINT NOT NULL DEFAULT 0,

    -- Lifetime total debited from the wallet (spend/transfers out).
    total_spent BIGINT NOT NULL DEFAULT 0,

    -- Last wallet state mutation timestamp.
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wallet_ledger_transactions (
    -- Transaction identifier (UUID string generated by app layer).
    id VARCHAR(36) PRIMARY KEY,

    -- Business type of transaction: earn, tip, bonus, spend, adjustment, reversal, etc.
    type VARCHAR(50) NOT NULL,

    -- Absolute transaction amount in coin units.
    amount BIGINT NOT NULL,

    -- Sender wallet owner for transfer-like operations; NULL for system mint/earn events.
    from_user_id VARCHAR(50) REFERENCES user_registration_data(id) ON DELETE SET NULL,

    -- Receiver wallet owner for transfer-like operations; NULL for sink/spend operations.
    to_user_id VARCHAR(50) REFERENCES user_registration_data(id) ON DELETE SET NULL,

    -- Optional idempotency/correlation reference (e.g., barterId, reviewId, jobId, external tx id).
    external_ref VARCHAR(255),

    -- Optional JSON payload as text for extensible metadata.
    metadata_json TEXT,

    -- Immutable creation time for audit ordering.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wallet_ledger_entries (
    -- Entry identifier (UUID string generated by app layer).
    id VARCHAR(36) PRIMARY KEY,

    -- Parent transaction; deleting transaction removes child entries.
    transaction_id VARCHAR(36) NOT NULL REFERENCES wallet_ledger_transactions(id) ON DELETE CASCADE,

    -- Wallet owner affected by this posting.
    user_id VARCHAR(50) NOT NULL REFERENCES user_registration_data(id) ON DELETE CASCADE,

    -- Signed delta applied to wallet balance (+ credit, - debit).
    delta BIGINT NOT NULL,

    -- Resulting available balance after this entry is applied.
    balance_after BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS wallet_coin_limits (
    -- Scope key for a limit profile (e.g., "global", "trusted", "new_users").
    id VARCHAR(100) PRIMARY KEY,

    -- Max amount user can transfer out per rolling day.
    max_daily_transfer BIGINT,

    -- Max amount allowed in a single transfer operation.
    max_single_transfer BIGINT,

    -- Max amount user can earn per rolling day (anti-abuse guard).
    max_daily_earn BIGINT,

    -- Minimum seconds between eligible coin actions.
    cooldown_seconds INT,

    -- Feature flag for this limit profile.
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    -- Last rule/profile update timestamp.
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Transaction lookup indexes
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_tx_type
    ON wallet_ledger_transactions(type);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_tx_from_user
    ON wallet_ledger_transactions(from_user_id);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_tx_to_user
    ON wallet_ledger_transactions(to_user_id);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_tx_external_ref
    ON wallet_ledger_transactions(external_ref);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_tx_created_at
    ON wallet_ledger_transactions(created_at DESC);

-- Entry lookup indexes
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_entries_tx_id
    ON wallet_ledger_entries(transaction_id);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_entries_user_id
    ON wallet_ledger_entries(user_id);

-- PostgreSQL schema comments for DB tooling and introspection
COMMENT ON TABLE wallets IS
    'Current wallet state per user for Barter Coins (fast read model).';

COMMENT ON COLUMN wallets.user_id IS
    'Wallet owner id; FK to user_registration_data.id.';
COMMENT ON COLUMN wallets.available_balance IS
    'Spendable balance in coin units.';
COMMENT ON COLUMN wallets.locked_balance IS
    'Reserved balance for future holds/escrow/disputes.';
COMMENT ON COLUMN wallets.total_earned IS
    'Lifetime credited amount for analytics and anti-abuse checks.';
COMMENT ON COLUMN wallets.total_spent IS
    'Lifetime debited amount for analytics and anti-abuse checks.';
COMMENT ON COLUMN wallets.updated_at IS
    'Timestamp of the latest wallet state change.';

COMMENT ON TABLE wallet_ledger_transactions IS
    'Immutable transaction headers for all wallet operations.';

COMMENT ON COLUMN wallet_ledger_transactions.id IS
    'Primary transaction identifier (UUID as text).';
COMMENT ON COLUMN wallet_ledger_transactions.type IS
    'Business transaction type (earn/tip/bonus/spend/adjustment/reversal/etc).';
COMMENT ON COLUMN wallet_ledger_transactions.amount IS
    'Absolute coin amount for this transaction.';
COMMENT ON COLUMN wallet_ledger_transactions.from_user_id IS
    'Source user for transfer/debit operations; null for system-issued credits.';
COMMENT ON COLUMN wallet_ledger_transactions.to_user_id IS
    'Destination user for transfer/credit operations; null for sink/spend flows.';
COMMENT ON COLUMN wallet_ledger_transactions.external_ref IS
    'External correlation/idempotency key for linking domain events.';
COMMENT ON COLUMN wallet_ledger_transactions.metadata_json IS
    'Extensible metadata payload serialized as JSON string.';
COMMENT ON COLUMN wallet_ledger_transactions.created_at IS
    'Immutable creation timestamp for audit ordering.';

COMMENT ON TABLE wallet_ledger_entries IS
    'Per-wallet postings produced by each transaction; supports balance auditing.';

COMMENT ON COLUMN wallet_ledger_entries.id IS
    'Primary ledger entry identifier (UUID as text).';
COMMENT ON COLUMN wallet_ledger_entries.transaction_id IS
    'Parent transaction id; FK to wallet_ledger_transactions.id.';
COMMENT ON COLUMN wallet_ledger_entries.user_id IS
    'Wallet owner affected by this entry.';
COMMENT ON COLUMN wallet_ledger_entries.delta IS
    'Signed amount change applied to wallet balance.';
COMMENT ON COLUMN wallet_ledger_entries.balance_after IS
    'Wallet balance immediately after applying this entry.';

COMMENT ON TABLE wallet_coin_limits IS
    'Configurable transfer/earn/cooldown rules for abuse prevention and policy tuning.';

COMMENT ON COLUMN wallet_coin_limits.id IS
    'Policy scope key (for example: global, trusted_users, new_users).';
COMMENT ON COLUMN wallet_coin_limits.max_daily_transfer IS
    'Maximum transferable amount per day for the scope.';
COMMENT ON COLUMN wallet_coin_limits.max_single_transfer IS
    'Maximum transferable amount per single transaction for the scope.';
COMMENT ON COLUMN wallet_coin_limits.max_daily_earn IS
    'Maximum earnable amount per day for the scope.';
COMMENT ON COLUMN wallet_coin_limits.cooldown_seconds IS
    'Minimum delay between coin operations for the scope.';
COMMENT ON COLUMN wallet_coin_limits.is_enabled IS
    'Whether this policy profile is active.';
COMMENT ON COLUMN wallet_coin_limits.updated_at IS
    'Timestamp of the latest policy profile change.';
